{% set name = "avalanche-lib" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 8d0886e76dbc2a769aa581aa879c711fcf7fa069291bb9986dffdd5d07f91d4a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools <=59.5.0
  run:
    - gdown
    - gputil
    - matplotlib-base
    - numpy
    - psutil
    - python >={{ python_min }},<3.11
    - pytorchcv
    - quadprog
    - scikit-learn
    - tensorboard >=1.15
    - pytorch
    - torchmetrics
    - torchvision
    - tqdm
    - typing-extensions
    - wandb >=0.18
    - gym
    - pycocotools
    - dill
    - lvis
    - qpsolvers

test:
  requires:
    - python {{ python_min }}
  imports:
    - avalanche

about:
  home: https://github.com/ContinualAI/avalanche
  summary: 'Avalanche: a Comprehensive Framework for Continual Learning Research'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
